### ISSUE TITLE
Purging stale files

### ISSUE THREAD

**Issue by ghost** [jdolan/quetoo-installer#1]
@jdolan Would appreciate your input on this.

Currently the updater doesn't remove stale files. In my local tree I've got a version that removes them after updating, but it seems like the java updater doesn't actually delete them. Does this want to be an option (off by default) and have it warn the user after updating if there are stale files?

Note that things like logs and crash dumps are considered stale as they go in the bin directory.

Another option is to have it store a list of all the files it has installed previously, and ensure that only things the installer created get removed.

**Comment by ghost** [comment]
Caching files would also allow it to purge the current directory (where README.md and .desktops are stored on Linux), which isn't done currently for obvious reasons.

**Comment by SpineyPete** [comment]
So my vote would be either...

A. Have a user/quetoo/purged/ dir which it first empties and then purges into it.
That way you can still retrieve accidentally purged files between updates. Permanently purged files should probably use the recycle bin. The updater should notify the user in case of a purge.

B. The data folder should probably be read only and the engine should warn the user to use the user/quetoo dir if it finds unexpected things during directory enumeration.

**Comment by ghost** [comment]
Per discussion in Discord, this is implemented for now as of ddae2af917349bab558d6dfb66ae3706fb83474d.
